### ISSUE TITLE
scikit-sparse usage

### ISSUE THREAD

**Issue by nmayorov** [antonior92/ip-nonlinear-solver#8]
Just an issue to discuss how `scikit-sparse` usage should be handled in scipy release.

Which way would be the best in your opinion?

**Comment by antonior92** [comment]
The ``normal equation approach`` (for which I needed scikit sparse for) actually does not have any significant advantages (This is indicated by the experimental results from first week).

 Therefore I think I could just remove this dependency (by removing the option ``normal equation`` from the functions ``projections``)

**Comment by nmayorov** [comment]
I think it is the best way. I suppose for now you would prefer to keep it?

**Comment by antonior92** [comment]
Lets keep it for now. I don't see any harm in it. And we may need it for something....

We can delete it a few weeks from now, at the time of my pull request to scipy.

**Comment by mdhaber** [comment]
I know you closed this, but I wanted to ask if there was anything wrong with putting the import in a try block (the except reporting that it is not available), and only if the normal equation approach is specifically requested in an options dict. I would argue to keep it in unless you have unequivocally shown that there is never an advantage... which is hard to to : )

**Comment by antonior92** [comment]
Sorry about closing the issue prematurely. 

I don't see anything wrong in providing the "normal equation approach" option to the user. It is already implemented and you have a point that it May have advantages in some situations that I am missing.
