### ISSUE TITLE
NonlinearConstraint, hess(x,v)

### ISSUE THREAD

**Issue by Yanyu000** [antonior92/ip-nonlinear-solver#9]
I don't understand it very well why there is "v" in hess(x,v) which is the hessian matrix of the constraint functions. For me, it's just a function about "x". Could you tell me how to derive that? Based on the example you provide.

**Comment by antonior92** [comment]
I think it is beacause the constraint is a multidimensional function from Rn to Rm. So we first take the dot product with v and then compute the hessian
